title: About
description: About the blog
theme: just-the-docs

url: https://github.com/subhsaha/subhsaha.github.io

aux_links: # remove if you don't want this link to appear on your pages
  LinkedIn: https://www.linkedin.com/in/subhasaha92
  Github: https://github.com/subhsaha
